<!-- levier_options.php -->
<option value="">Réinitialiser les Filtres</option>
<option value="MFG L1 : PLM">MFG L1 : PLM</option>
<option value="MFG L2 : ERP">MFG L2 : ERP</option>
<option value="MFG L3 : MES & D. Scheduling">MFG L3 : MES & D. Scheduling</option>
<option value="MFG L4 : MCS & 5G & WIFI 6E">MFG L4 : MCS & 5G & WIFI 6E</option>
<option value="MFG L5 : Digital Twins">MFG L5 : Digital Twins</option>
<option value="MFG L6 : Lean 4.0 Methods">MFG L6 : Lean 4.0 Methods</option>
<option value="MFG L7 : Lean 4.0 Tools">MFG L7 : Lean 4.0 Tools</option>
<option value="MFG L8 : Lean 4.0 Teams">MFG L8 : Lean 4.0 Teams</option>
<option value="MFG L9 : IT-RB & Cyber">MFG L9 : IT-RB & Cyber</option>
<option value="MFG L10 : Closed Door Equipment">MFG L10 : Closed Door Equipment</option>
<option value="MFG L11 : Manufacturing Data analysis">MFG L11 : Manufacturing Data analysis</option>
<option value="MFG L12 : Cobots & Robots">MFG L12 : Cobots & Robots</option>
<option value="MFG L13 : Augmented Reality">MFG L13 : Augmented Reality</option>
<option value="MFG L14 : Digital Inspection & Automated Decision">MFG L14 : Digital Inspection & Automated Decision</option>
<option value="MFG L15 : Marking & Traceability">MFG L15 : Marking & Traceability</option>
<option value="MFG L16 : IIOT">MFG L16 : IIOT</option>
<option value="MFG L17 : CMMS & Remote maintenance">MFG L17 : CMMS & Remote maintenance</option>
<option value="MFG L18 : FMS & BIM">MFG L18 : FMS & BIM</option>
<option value="MFG L18 : Supply Chain 4.0">MFG L18 : Supply Chain 4.0</option>
<option value="ENG LX : Project Management">ENG LX : Project Management</option>
<option value="ENG LX : Agile">ENG LX : Agile</option>
<option value="ENG LX : Development Cockpit & Design to Value">ENG LX : Development Cockpit & Design to Value</option>
<option value="ENG LX : Virtual & Augmented Reality">ENG LX : Virtual & Augmented Reality</option>
<option value="ENG LX : Remote collaboration">ENG LX : Remote collaboration</option>
<option value="ENG LX : MBSE">ENG LX : MBSE</option>
<option value="ENG LX : Software">ENG LX : Software</option>
<option value="ENG LX : Model Based Definition">ENG LX : Model Based Definition</option>
<option value="ENG LX : Industrialisation tools">ENG LX : Industrialisation tools</option>
<option value="ENG LX : Services authoring tools">ENG LX : Services authoring tools</option>
<option value="ENG LX : Data analytics">ENG LX : Data analytics</option>
<option value="ENG LX : Simulation Tools">ENG LX : Simulation Tools</option>
<option value="ENG LX : PLM - As-required">ENG LX : PLM - As-required</option>
<option value="ENG LX : PLM - As-designed">ENG LX : PLM - As-designed</option>
<option value="ENG LX : PLM - As-planned / As-built">ENG LX : PLM - As-planned / As-built</option>
<option value="ENG LX : PLM - As-to be maintained / As-maintained">ENG LX : PLM - As-to be maintained / As-maintained</option>
<option value="ENG LX : Simulations management">ENG LX : Simulations management</option>
<option value="ENG LX : Tests Management">ENG LX : Tests Management</option>
<option value="ENG LX : Materials and Processis Database a LIMS">ENG LX : Materials and Processis Database a LIMS</option>
<option value="EEX LX : New Attitudes">EEX LX : New Attitudes</option>
<option value="EEX LX : Leadership Model Evolution">EEX LX : Leadership Model Evolution</option>
<option value="EEX LX : HR processes adaptation">EEX LX : HR processes adaptation</option>
<option value="EEX LX : Well being @e-work">EEX LX : Well being @e-work</option>
<option value="EEX LX : New Internal rules">EEX LX : New Internal rules</option>
<option value="EEX LX : Digital Competencies">EEX LX : Digital Competencies</option>
<option value="EEX LX : Digital Learning">EEX LX : Digital Learning</option>
<option value="EEX LX : Digital resources management">EEX LX : Digital resources management</option>
<option value="EEX LX : Learning Material">EEX LX : Learning Material</option>
<option value="EEX LX : Collaborations & innovation studio">EEX LX : Collaborations & innovation studio</option>
<option value="EEX LX : Team work 4.0">EEX LX : Team work 4.0</option>
<option value="EEX LX : Professional social network 4.0">EEX LX : Professional social network 4.0</option>
<option value="EEX LX : LiveChat / Webinars">EEX LX : LiveChat / Webinars</option>
<option value="EEX LX : Simplified UX">EEX LX : Simplified UX</option>
<option value="EEX LX : Easy Access">EEX LX : Easy Access</option>
<option value="EEX LX : Communication & Services Portal">EEX LX : Communication & Services Portal</option>
<option value="EEX LX : Ideation & Engagement Tools">EEX LX : Ideation & Engagement Tools</option>
<option value="SSS LX : Dispatch Reliability Advanced services">SSS LX : Dispatch Reliability Advanced services</option>
<option value="SSS LX : Remote inspection / remote assistance">SSS LX : Remote inspection / remote assistance</option>
<option value="SSS LX : 3D AR / VR Training">SSS LX : 3D AR / VR Training</option>
<option value="SSS LX : Advanced Contracts control system">SSS LX : Advanced Contracts control system</option>
<option value="SSS LX : Spare parts advanced SCM">SSS LX : Spare parts advanced SCM</option>
<option value="SSS LX : Spare parts data exchange">SSS LX : Spare parts data exchange</option>
<option value="SSS LX : Smart MRO">SSS LX : Smart MRO</option>
<option value="SSS LX : Sales e-tools">SSS LX : Sales e-tools</option>
<option value="SSS LX : RPA">SSS LX : RPA</option>
<option value="SSS LX : CRM">SSS LX : CRM</option>
<option value="SSS LX : Customer Portal">SSS LX : Customer Portal</option>
<option value="SSS LX : PLM">SSS LX : PLM</option>
<option value="SSS LX : ERP+">SSS LX : ERP+</option>
<option value="SSS LX : Technical Documentation">SSS LX : Technical Documentation</option>
<option value="Autre">Autre</option>
<option value="Intelligence Artificielle">Intelligence Artificielle</option>
<option value="KPI Transverse">KPI Transverse</option>
<option value="Roadmap">Roadmap</option>




